# -*- coding: utf-8 -*-
"""Clarify2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o-iuhjKMe7-3SGwJEOZLqJawQ9S6negn
"""

import random
import time

def montarBaralho():
  baralho = []
  cores = ["Vermelho", "Verde", "Amarelo", "Azul"]
  valores = [0,1,2,3,4,5,6,7,8,9, "+2", "Pular", "Inverter"]
  coringas = ["Escolher", "+4"]
  for cor in cores:
    for valor in valores:
      carta = "{} {}".format(cor,valor)
      baralho.append(carta)
  for i in range(4):
    baralho.append(coringas[0])
    baralho.append(coringas[1])
  return baralho
def embaralharBaralho(baralho):
  for cartaPos in range(len(baralho)):
    random.shuffle(baralho)
  return baralho
def virarCartas(numCartas):
  cartaVirada = []
  for x in range(numCartas):
    cartaVirada.append(baralhoMonte.pop(0))
  return cartaVirada
def mostrarMao(jogador, maoJogador):
  print("Vez de {} jogar:".format(jogadorNome[jogador]))
  time.sleep(10)
  print("Suas Cartas:")
  print("------------------")
  y = 1
  for carta in maoJogador:
    print("{}) {}".format (y, carta))
    y += 1
    print("")
def jogada(cor, valor, maoJogador):
  for carta in maoJogador:
    if "coringas" in carta:
      return True
    elif cor in carta or valor in carta:
      return True
  return False
baralhoMonte = montarBaralho()
baralhoMonte = embaralharBaralho(baralhoMonte)
baralhoMonte = embaralharBaralho(baralhoMonte)
descartadas = []
jogadorNome = []
jogadores = []
cores = ["Vermelho", "Verde", "Amarelo", "Azul"]
numeroJogadores = int(input("Quantos jogadores?"))
while numeroJogadores < 2 or numeroJogadores > 5:
    numeroJogadores = int(input("Invalido. Escolha um valor entre 2 e 5.\nQuantos Jogadores?"))
for jogador in range(numeroJogadores):
  jogadorNome.append(input("Qual o nome do {} jogador?".format(jogador+1)))
  jogadores.append(virarCartas(5))
vezJogador = 0
direcao = 1
jogando = True
descartadas.append(baralhoMonte.pop(0))
separarCarta = descartadas[0].split(" ",1)
corAtual = separarCarta[0]
if corAtual != "coringas":
  valorCarta = separarCarta[1]
else:
  valorCarta = "Qualquer"
while jogando:
  mostrarMao(vezJogador, jogadores[vezJogador])
  print("Carta no topo da pilha: {}".format(descartadas[-1]))
  if jogada(corAtual, valorCarta, jogadores [vezJogador]):
    cartaEscolhida = int(input("Qual carta voce deseja jogar?"))
    while not jogada(corAtual, valorCarta, [jogadores[vezJogador][cartaEscolhida-1]]):
      cartaEscolhida = int(input("Não é uma carta válida? Escolha outra carta."))
    print("Voce escolheu {}".format(jogadores[vezJogador][cartaEscolhida-1]))
    descartadas.append(jogadores[vezJogador].pop(cartaEscolhida-1))

    if len(jogadores[vezJogador]) == 0:
      jogando = False
      vencedor = jogadorNome[vezJogador]
    else:
      separarCarta = descartadas[-1].split(" ",1)
      corAtual= separarCarta[1]
    if corAtual == "coringas":
      for x in range(len(cores)):
        print("{)} {}".format(x+1, cores[x]))
        novaCor = int(input("Qual a cor voce quer de escolher?"))
        while novaCor < 1 or novaCor > 4:
          novaCor = int(input("Opção inválida. Qual cor voce quer escolher?"))
        corAtual = cores[novaCor-1]
    if valorCarta == "Inverter":
      direcao = direcao * -1
    elif valorCarta =="Pular":
      vezJogador += direcao
      if vezJogador >= numeroJogadores:
        vezJogador = 0
      elif vezJogador < 0:
        vezJogador = numeroJogadores-1
    print("")
  else:
    print("Voce nao pode jogar. Voce deve comprar uma carta")
    jogadores[vezJogador].extend(virarCartas(1))
  vezJogador += direcao
  if vezJogador >= numeroJogadores:
        vezJogador = 0
  elif vezJogador < 0:
        vezJogador = numeroJogadores-1
print("Fim de Jogo")
print("{} é o vencedor!".format(vencedor))
